platform :ios, "9.0" 
target 'RuiSi' do
    pod 'AFNetworking'
    pod 'DTCoreText','~> 1.6.19'
    pod 'RegexKitLite','~> 4.0'
    pod 'TTTAttributedLabel', '~> 2.0.0'
	pod 'SVProgressHUD'
    pod 'SDWebImage','~> 3.8.2'
    pod 'BlocksKit','~> 2.2.5'
    pod 'MJRefresh','~> 3.1.12'
    pod 'libextobjc','~> 0.4.1'
	pod 'Objective-C-HMTL-Parser'
    pod 'Masonry'
end
