platform :ios, "9.0" 
target 'RuiSi' do
    pod 'AFNetworking','~> 3.2.0’
    pod 'DTCoreText','~> 1.6.19'
    pod 'RegexKitLite','~> 4.0'
    pod 'SVProgressHUD','~> 2.2.5’
    pod 'SDWebImage','~> 4.3.3’
    pod 'BlocksKit','~> 2.2.5'
    pod 'SDWebImage/GIF','~> 4.3.3’
    pod 'MJRefresh','~> 3.1.12'
    pod 'libextobjc','~> 0.4.1'
    pod 'Objective-C-HMTL-Parser','~> 0.0.1’
    pod 'Masonry','~> 1.1.0’
    pod 'PureLayout','~> 3.0.2’
end
